name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/ryenjohn/ubuntu-v1:latest .

      - name: Push Docker image
        run: docker push ghcr.io/ryenjohn/ubuntu-v1:latest
        
      - name: Mock Deployment Step (Docker Compose)
        run: |
          echo "deployment..."
          echo "docker pull ghcr.io/ryenjohn/ubuntu-v1:latest"
          echo "docker compose up -d"
          echo "Deployment completed (mock)."
