
on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push Images
        run: |
          docker login --username ryenjohn --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f workspace/Dockerfile -t ghcr.io/ryenjohn/hello-world-ghcr:latest .
          docker push ghcr.io/ryenjohn/hello-world-ghcr:latest
