name: Docker Image CI for ghcr

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build and Push Images
        run: | 
          docker login --username ryenjohn --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/ryenjohn/hello-world-ghcr:latest
          docker push ghcr.io/ryenjohn/hello-world-ghcr:latest
